/**************************************************************
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 *************************************************************/
package org.openoffice.extensions.projecttemplates.component;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.nodes.Node;
import org.openide.util.NbBundle;
import org.openoffice.extensions.util.datamodel.NbNodeObject;
import org.openoffice.extensions.util.typebrowser.logic.UnoTypes;
import org.openoffice.extensions.util.typebrowser.logic.TypeBrowserChildren;
import org.openoffice.extensions.util.typebrowser.logic.TypeNode;

/**
 *
 * @author  sg128468
 */
public class NewTypeBrowserDialog extends javax.swing.JPanel 
        implements ExplorerManager.Provider, ActionListener {
    
    private ExplorerManager manager = new ExplorerManager();

    private TypeNode rootNode;

    private ComponentPanelVisual2IdlFiles comp;
    private ComponentWizardPanel2IdlFiles panel;

    /** Creates new form NewTypeBrowserDialog */
    public NewTypeBrowserDialog(Component component, ComponentWizardPanel2IdlFiles panel) {
        initComponents();
        this.comp = (ComponentPanelVisual2IdlFiles)component;
        this.panel = panel;
        
        this.rootNode = TypeNode.createRootNode(
                new String[] {UnoTypes.MODULE, 
                              UnoTypes.INTERFACE,
                              UnoTypes.SERVICE,
                }
        );
        
        manager.setRootContext(rootNode);
        
        BeanTreeView typeView = (BeanTreeView)jScrollPane1;
        if (rootNode.getChildren().getNodesCount() != 0)
            typeView.setRootVisible(false);
        else
            typeView.setRootVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new BeanTreeView();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jScrollPane1.setName("typeBrowserList"); // NOI18N

        jLabel1.setLabelFor(jComboBox1);
        jLabel1.setText(NbBundle.getMessage(ComponentWizardIterator.class, "LBL_Show")); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Services", "Interfaces" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        int index = jComboBox1.getSelectedIndex();
        switch(index) {
            case 1:
                rootNode.setDisplayedTypes(new String[]{
                    UnoTypes.MODULE, 
                    UnoTypes.SERVICE,});
                break;
            case 2:
                rootNode.setDisplayedTypes(new String[]{
                    UnoTypes.MODULE, 
                    UnoTypes.INTERFACE,
                });
                break;
            default:
                rootNode.setDisplayedTypes(new String[]{
                    UnoTypes.MODULE, 
                    UnoTypes.INTERFACE,
                    UnoTypes.SERVICE,                
                });
        }
        Node node = manager.getExploredContext();
        if (node == null) {
            node = manager.getRootContext();
        }
        TypeBrowserChildren tbc = (TypeBrowserChildren)node.getChildren();
        tbc.update();
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    /**
     */
    public static void start(final Component component, final ComponentWizardPanel2IdlFiles panel) {
        
        NewTypeBrowserDialog typeBrowser = new NewTypeBrowserDialog(component, panel);
        
        DialogDescriptor ddscr = new DialogDescriptor(typeBrowser,
                NbBundle.getMessage(ComponentWizardIterator.class, "LBL_TypeBrowser_Title"));

        typeBrowser.addDialogDescriptor(ddscr);
        
        Dialog d = DialogDisplayer.getDefault().createDialog(ddscr);
        d.setVisible(true);
    }

    public ExplorerManager getExplorerManager() {
        return manager;
    }

    private void addDialogDescriptor(DialogDescriptor ddsc) {
//        this.dialogDescriptor = ddsc;
        ddsc.setButtonListener(this);

        // set help context eventually
//        dialogDescriptor.setHelpCtx(new HelpCtx("helpCtxString")); // NOI18N  
    }
    
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("OK")) { // NOI18N
            Node[] nodes = manager.getSelectedNodes();
            for (int i=0; i<nodes.length; i++) {
                TypeNode node = (TypeNode)nodes[i];
                comp.addNewServiceOrInterface(node.getHierarchicalName(), node.getNodeType(), node.isOwnDesign());
            }
            if (panel != null)
                panel.fireChangeEvent();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
