/**
 * ************************************************************
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership. The ASF
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 ************************************************************
 */
package org.openoffice.extensions.projecttemplates.calcaddin;

import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileSystemView;
import javax.swing.text.Document;
import org.netbeans.spi.project.ui.support.ProjectChooser;
import org.openide.WizardDescriptor;
import org.openide.WizardValidationException;
import org.openide.filesystems.FileUtil;
import org.openide.util.NbBundle;
import org.openoffice.extensions.config.ConfigurationSettings;

public class AddinPanelVisual1Project extends JPanel implements DocumentListener {

    public static final String PROP_PROJECT_NAME = "AddIn"; // NOI18N

    private boolean addinNameModified = false;
    private AddinWizardPanel1Project panel;

    private String[] generatedFiles = new String[]{"", "", "",
        "src/uno-extension-manifest.xml\n",
        "registry/data/org/openoffice/Office/CalcAddins.xcu\n"}; // NOI18N

    /**
     * Creates new form PanelProjectLocationVisual
     */
    public AddinPanelVisual1Project(AddinWizardPanel1Project panel) {
        initComponents();
        this.panel = panel;
        // Register listener on the textFields to make the automatic updates
        projectNameTextField.getDocument().addDocumentListener(this);
        projectLocationTextField.getDocument().addDocumentListener(this);
        // Register listener on the textFields to make the automatic updates
        calcAddinNameTextField.getDocument().addDocumentListener(this);
        packageTextField.getDocument().addDocumentListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectNameLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        addinNameLabel = new javax.swing.JLabel();
        calcAddinNameTextField = new javax.swing.JTextField();
        packageLabel = new javax.swing.JLabel();
        packageTextField = new javax.swing.JTextField();
        projectLocationLabel = new javax.swing.JLabel();
        projectLocationTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        createdFolderLabel = new javax.swing.JLabel();
        createdFolderTextField = new javax.swing.JTextField();
        createdFilesLabel = new javax.swing.JLabel();
        createdFilesPane = new javax.swing.JTextPane();

        projectNameLabel.setLabelFor(projectNameTextField);
        org.openide.awt.Mnemonics.setLocalizedText(projectNameLabel, NbBundle.getMessage(AddinPanelVisual1Project.class, "LBL_ProjectName")); // NOI18N

        projectNameTextField.setToolTipText(NbBundle.getMessage(AddinPanelVisual1Project.class, "TF_ProjectName_Tooltip")); // NOI18N

        addinNameLabel.setLabelFor(calcAddinNameTextField);
        org.openide.awt.Mnemonics.setLocalizedText(addinNameLabel, NbBundle.getMessage(AddinWizardIterator.class, "LB_CalcAddinName")); // NOI18N

        calcAddinNameTextField.setToolTipText(NbBundle.getMessage(AddinWizardIterator.class, "TF_CalcAddinName_Tooltip")); // NOI18N

        packageLabel.setLabelFor(packageTextField);
        org.openide.awt.Mnemonics.setLocalizedText(packageLabel, NbBundle.getMessage(AddinWizardIterator.class, "LB_PackageName")); // NOI18N

        packageTextField.setToolTipText(NbBundle.getMessage(AddinWizardIterator.class, "TF_PackageName_Tooltip")); // NOI18N

        projectLocationLabel.setLabelFor(projectLocationTextField);
        org.openide.awt.Mnemonics.setLocalizedText(projectLocationLabel, NbBundle.getMessage(AddinPanelVisual1Project.class, "LBL_ProjectLocation")); // NOI18N

        projectLocationTextField.setToolTipText(NbBundle.getMessage(AddinPanelVisual1Project.class, "TF_ProjectLocation_Tooltip")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(browseButton, NbBundle.getMessage(AddinPanelVisual1Project.class, "LBL_BUTTON_Browse")); // NOI18N
        browseButton.setToolTipText(NbBundle.getMessage(AddinPanelVisual1Project.class, "BUTTON_Browse_Tooltip")); // NOI18N
        browseButton.setActionCommand("BROWSE");
        browseButton.setName("browse"); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        createdFolderLabel.setLabelFor(createdFolderTextField);
        org.openide.awt.Mnemonics.setLocalizedText(createdFolderLabel, NbBundle.getMessage(AddinPanelVisual1Project.class, "LBL_ProjectFolder")); // NOI18N

        createdFolderTextField.setEditable(false);
        createdFolderTextField.setToolTipText(NbBundle.getMessage(AddinPanelVisual1Project.class, "TF_ProjectFolder_Tooltip")); // NOI18N
        createdFolderTextField.setFocusable(false);

        createdFilesLabel.setLabelFor(createdFilesPane);
        org.openide.awt.Mnemonics.setLocalizedText(createdFilesLabel, NbBundle.getMessage(AddinWizardIterator.class, "LB_CreatedFiles")); // NOI18N

        createdFilesPane.setBackground(new java.awt.Color(236, 233, 216));
        createdFilesPane.setBorder(null);
        createdFilesPane.setEditable(false);
        createdFilesPane.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectNameLabel)
                    .addComponent(packageLabel)
                    .addComponent(addinNameLabel)
                    .addComponent(projectLocationLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(createdFilesLabel)
                        .addComponent(createdFolderLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(calcAddinNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(createdFolderTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(packageTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(projectLocationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addComponent(browseButton))
                    .addComponent(createdFilesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addinNameLabel)
                    .addComponent(calcAddinNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageLabel)
                    .addComponent(packageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLocationLabel)
                    .addComponent(projectLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createdFolderLabel)
                    .addComponent(createdFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createdFilesLabel)
                        .addGap(165, 165, 165))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createdFilesPane, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser chooser = new JFileChooser(FileSystemView.getFileSystemView());
        FileUtil.preventFileChooserSymlinkTraversal(chooser, ConfigurationSettings.getDefaultFileChooserStartingDir());
        chooser.setDialogTitle(NbBundle.getMessage(AddinWizardIterator.class, "LB_FileChooserTitle"));
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        String path = this.projectLocationTextField.getText();
        if (path.length() > 0) {
            File f = new File(path);
            if (f.exists()) {
                chooser.setSelectedFile(f);
            }
        }
        if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
            File projectDir = chooser.getSelectedFile();
            ConfigurationSettings.storeDefaultFileChooserStartingDir(projectDir);
            projectLocationTextField.setText(FileUtil.normalizeFile(projectDir).getAbsolutePath());
        }
        panel.fireChangeEvent();

    }//GEN-LAST:event_browseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addinNameLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField calcAddinNameTextField;
    private javax.swing.JLabel createdFilesLabel;
    private javax.swing.JTextPane createdFilesPane;
    private javax.swing.JLabel createdFolderLabel;
    private javax.swing.JTextField createdFolderTextField;
    private javax.swing.JLabel packageLabel;
    private javax.swing.JTextField packageTextField;
    private javax.swing.JLabel projectLocationLabel;
    private javax.swing.JTextField projectLocationTextField;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    // End of variables declaration//GEN-END:variables

    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
        projectNameTextField.requestFocus();
    }

    boolean valid(WizardDescriptor wizardDescriptor) {

        if (!panel.getAddInWizardIterator().isSdkOk()) {
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LBL_ErrorMessageOfficeSdk");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false; // Office or SDK skipped during Configuration Panel
        }

        if (projectNameTextField.getText().length() == 0) {
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LB_Error_ProjectName");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false; // Display name not specified
        }
        File f = FileUtil.normalizeFile(new File(projectLocationTextField.getText()).getAbsoluteFile());
        if (!f.isDirectory()) {
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LB_Error_ProjectFolderPath");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false;
        }
        final File destFolder = FileUtil.normalizeFile(new File(createdFolderTextField.getText()).getAbsoluteFile());

        File projLoc = destFolder;
        while (projLoc != null && !projLoc.exists()) {
            projLoc = projLoc.getParentFile();
        }
        if (projLoc == null || !projLoc.canWrite()) {
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LB_Error_CreateProjectFolder");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false;
        }

        if (FileUtil.toFileObject(projLoc) == null) {
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LB_Error_ProjectFolderPath");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false;
        }

        File[] kids = destFolder.listFiles();
        if (destFolder.exists() && kids != null && kids.length > 0) {
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LB_Error_ProjectFolderNotEmpty");
            // Folder exists and is not empty
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false;
        }

        String mainClass = calcAddinNameTextField.getText().trim();
        if (mainClass.length() == 0 || !mainClass.matches("[a-zA-Z_][a-zA-Z._$0-9]*")) { // NOI18N
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LB_Error_AddInClassName");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false; // Display name not specified
        }
        String packageName = packageTextField.getText().trim();
        if (packageName.length() == 0 || !packageName.matches("[a-zA-Z_]((\\.[a-zA-Z_0-9]++)|[a-zA-Z_0-9])*")) { // NOI18N
            String message = NbBundle.getMessage(AddinWizardIterator.class, "LB_Error_PackageName");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false; // Display name not specified
        }

        wizardDescriptor.putProperty("WizardPanel_errorMessage", ""); // NOI18N
        return true;
    }

    void store(WizardDescriptor d) {
        String name = projectNameTextField.getText().trim();
        String folder = createdFolderTextField.getText().trim();
        try {
            d.putProperty("projdir", new File(folder)); // NOI18N
            d.putProperty("name", name); // NOI18N
            d.putProperty("ProjectDir", new File(folder).getCanonicalPath()); // NOI18N
            d.putProperty("ProjectName", name); // NOI18N
            d.putProperty("ProjectDisplayName", name); // NOI18N
        } catch (IOException e) {
            // TODO
        }

        String mainClass = calcAddinNameTextField.getText().trim();
        String packageName = packageTextField.getText().trim();
        d.putProperty("mainClassName", mainClass); // NOI18N
        d.putProperty("displayName", mainClass); // NOI18N
        d.putProperty("packageName", packageName);  // NOI18N
        d.putProperty("RegistrationClass", packageName + "." + mainClass + "Impl");  // NOI18N
        d.putProperty("UnoPackage", packageName); // NOI18N
    }

    private void updateCreatedFiles() {
        createdFilesPane.setText(generatedFiles[0] + generatedFiles[1]
                + generatedFiles[2] + generatedFiles[3]
                + generatedFiles[4]); // NOI18N
    }

    void read(WizardDescriptor settings) {
        File projectLocation = (File) settings.getProperty("projdir"); // NOI18N
        if (projectLocation == null || projectLocation.getParentFile() == null || !projectLocation.getParentFile().isDirectory()) {
            projectLocation = ProjectChooser.getProjectsFolder();
        } else {
            projectLocation = projectLocation.getParentFile();
        }
        this.projectLocationTextField.setText(projectLocation.getAbsolutePath());

        String projectName = (String) settings.getProperty("name"); // NOI18N
        if (projectName == null) {
            projectName = "AddIn"; // NOI18N
            String[] fileList = projectLocation.list(new FilenameFilter() {
                public boolean accept(File dir, String name) {
                    if (name.startsWith("AddIn")) {
                        return true; // NOI18N
                    }
                    return false;
                }
            });
            boolean searchProjectName = true;
            int length = projectName.length();
            for (int i = 0; searchProjectName && i < fileList.length + 1; i++) {
                switch (i) {
                    case 0: // keep project name
                        break;
                    case 1: // append 1
                        projectName = new StringBuffer(projectName).append(1).toString();
                        break;
                    default: // remove number and append the next one
                        projectName = new StringBuffer(projectName.substring(0, length)).append(i).toString();
                }
                // test if the name is already used
                searchProjectName = false;
                for (int j = 0; !searchProjectName && j < fileList.length; j++) {
                    // if the project name isn't found, searchProjectName stays false and the name is kept
                    searchProjectName |= fileList[j].equals(projectName);
                }
            }
        }
        this.projectNameTextField.setText(projectName);
        this.projectNameTextField.selectAll();

        String mainclass = (String) settings.getProperty("mainClassName"); // NOI18N
        if (mainclass == null) {
            mainclass = projectName;
        }
        calcAddinNameTextField.setText(projectName);

        String packagename = (String) settings.getProperty("packageName"); // NOI18N
        if (packagename == null) {
            packagename = NbBundle.getMessage(ConfigurationSettings.class, "default.package"); // NOI18N
        }
        packageTextField.setText(packagename);

        updateCreatedFiles();
    }

    void validate(WizardDescriptor d) throws WizardValidationException {
        // nothing to validate
    }

    // Implementation of DocumentListener --------------------------------------
    public void changedUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    public void insertUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    public void removeUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    /**
     * Handles changes in the Project name and project directory,
     */
    private void updateTexts(DocumentEvent e) {

        Document doc = e.getDocument();

        if (doc == calcAddinNameTextField.getDocument() && calcAddinNameTextField.getText().length() > 0) {
            if (!projectNameTextField.getText().equals(calcAddinNameTextField.getText())) {
                addinNameModified = true;
            }
        }

        if (doc == projectNameTextField.getDocument() || doc == projectLocationTextField.getDocument()
                || doc == packageTextField.getDocument()) {
//            doc == calcAddinNameTextField.getDocument() || doc == packageTextField.getDocument()) {
            // Change in the project name

            String projectName = projectNameTextField.getText();
            String projectFolder = projectLocationTextField.getText();

            if (!addinNameModified) {
                calcAddinNameTextField.setText(projectName);
            }

            //if (projectFolder.trim().length() == 0 || projectFolder.equals(oldName)) {
            createdFolderTextField.setText(projectFolder.concat(File.separator).concat(projectName));
            //}

            String packagePath = "src/" + packageTextField.getText().replace('.', '/') + '/'; // NOI18N
            generatedFiles[0] = packagePath + calcAddinNameTextField.getText() + "Impl.java\n"; // NOI18N
            generatedFiles[1] = packagePath + calcAddinNameTextField.getText() + ".idl\n"; // NOI18N
            generatedFiles[2] = packagePath + "X" + calcAddinNameTextField.getText() + ".idl\n"; // NOI18N

            updateCreatedFiles();
        }
        if (doc == calcAddinNameTextField.getDocument()) {
            String packagePath = "src/" + packageTextField.getText().replace('.', '/') + '/'; // NOI18N
            generatedFiles[0] = packagePath + calcAddinNameTextField.getText() + "Impl.java\n"; // NOI18N
            generatedFiles[1] = packagePath + calcAddinNameTextField.getText() + ".idl\n"; // NOI18N
            generatedFiles[2] = packagePath + "X" + calcAddinNameTextField.getText() + ".idl\n"; // NOI18N
            updateCreatedFiles();
        }
        panel.fireChangeEvent(); // Notify that the panel changed
    }

}
