/**************************************************************
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 *************************************************************/

package org.openoffice.extensions.projecttemplates.addon;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;
import java.util.HashSet;
import javax.swing.ActionMap;
import javax.swing.JPanel;
import javax.swing.tree.TreeSelectionModel;
import org.openide.WizardDescriptor;
import org.openide.WizardValidationException;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.explorer.view.TreeTableView;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openoffice.extensions.projecttemplates.addon.datamodel.AddOn;
import org.openoffice.extensions.projecttemplates.addon.datamodel.Command;
import org.openoffice.extensions.projecttemplates.addon.datamodel.node.AddOnNode;
import org.openoffice.extensions.projecttemplates.addon.datamodel.node.AddOnTreeCreator;
import org.openoffice.extensions.util.datamodel.localization.LanguageDefinition;
import org.openoffice.extensions.util.datamodel.properties.LocalizedOpenOfficeOrgProperty;
import org.openoffice.extensions.util.datamodel.NbNodeObject;
//import org.openoffice.extensions.projecttemplates.calcaddin.datamodel.node.AddInNode;
//import org.openoffice.extensions.projecttemplates.calcaddin.datamodel.node.AddInTreeCreator;
import org.openoffice.extensions.util.LogWriter;
import org.openoffice.extensions.util.datamodel.actions.BaseAction;
import org.openoffice.extensions.util.datamodel.properties.UnknownOpenOfficeOrgPropertyException;

public class AddOnPanelVisual2Description extends JPanel implements 
        ExplorerManager.Provider, PropertyChangeListener {
    
    public static final String PROP_PROJECT_NAME = "descFirst"; // NOI18N
    
    private ExplorerManager manager = new ExplorerManager();
    private PropertySheet propSheet;
    private Lookup lookup;
    
    private AddOnActions actions;
    private AddOnWizardPanel2Description panel;
    
    /** Creates new form PanelProjectLocationVisual */
    public AddOnPanelVisual2Description(AddOnWizardPanel2Description panel) {
        initComponents();
        
        this.panel = panel;

        AddOnNode node = AddOnTreeCreator.createInitialFunctionTree();
        manager.setRootContext(node);
        
        TreeTableView view = (TreeTableView)jScrollPane1;
        view.setRootVisible(false);
        view.setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        
        // for keyboard actions enable this: handle actions must be done, too
        ActionMap map = getActionMap();
//        map.put("delete", ExplorerUtils.actionDelete(manager, true)); // NOI18N

        propSheet = (PropertySheet)jPanel1;
        // this does not seem to work; commented -> later version of NB?
//        propSheet.addPropertyChangeListener(this);  
        
        actions = new AddOnActions(manager, panel);
        // deliver the actual actions to the node-actions
        AddOnNode rootNode = (AddOnNode)manager.getRootContext();
        rootNode.setActions((BaseAction)actions);
        
        manager.addPropertyChangeListener(this);
        lookup = ExplorerUtils.createLookup(manager, map);
    }
    
    public ExplorerManager getExplorerManager() {
        return manager;
    }
   
    public Lookup getLookup() {
        return lookup;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new PropertySheet();
        jScrollPane1 = new TreeTableView();
        addFunctionButton = new javax.swing.JButton();
        deleteLanguageButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        addLanguageButton = new javax.swing.JButton();

        setAutoscrolls(true);
        setRequestFocusEnabled(false);
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setForeground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(5, 10));
        jPanel1.setName("properties");
        jPanel1.setPreferredSize(new java.awt.Dimension(5, 10));
        jSplitPane1.setRightComponent(jPanel1);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setFocusTraversalPolicy(getFocusTraversalPolicy());
        jScrollPane1.setMinimumSize(new java.awt.Dimension(5, 10));
        jScrollPane1.setName("commands");
        jScrollPane1.setPreferredSize(new java.awt.Dimension(5, 10));
        jSplitPane1.setLeftComponent(jScrollPane1);

        org.openide.awt.Mnemonics.setLocalizedText(addFunctionButton, org.openide.util.NbBundle.getMessage(AddOnWizardIterator.class, "LBL_BUTTON_AddCommand"));
        addFunctionButton.setToolTipText(NbBundle.getMessage(AddOnPanelVisual2Description.class, "BUTTON_AddFunction_Tooltip"));
        addFunctionButton.setName("addCommand");
        addFunctionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFunctionButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(deleteLanguageButton, org.openide.util.NbBundle.getMessage(AddOnWizardIterator.class, "LBL_BUTTON_DeleteLanguage"));
        deleteLanguageButton.setToolTipText(NbBundle.getMessage(AddOnPanelVisual2Description.class, "BUTTON_DeleteLang_Tooltip"));
        deleteLanguageButton.setName("deleteLanguage");
        deleteLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLanguageButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(deleteButton, org.openide.util.NbBundle.getMessage(AddOnPanelVisual2Description.class, "LBL_BUTTON_Delete"));
        deleteButton.setToolTipText(NbBundle.getMessage(AddOnPanelVisual2Description.class, "BUTTON_Delete_Tooltip"));
        deleteButton.setName("deleteCommand");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(addLanguageButton, org.openide.util.NbBundle.getMessage(AddOnWizardIterator.class, "LBL_BUTTON_AddLanguage"));
        addLanguageButton.setToolTipText(NbBundle.getMessage(AddOnPanelVisual2Description.class, "BUTTON_AddLang_Tooltip"));
        addLanguageButton.setName("addLanguage");
        addLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLanguageButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(addFunctionButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(deleteButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(deleteLanguageButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(addLanguageButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(addFunctionButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deleteButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 364, Short.MAX_VALUE)
                .add(addLanguageButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(deleteLanguageButton))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLanguageButtonActionPerformed

        actions.deleteLanguageAction();
        
    }//GEN-LAST:event_deleteLanguageButtonActionPerformed

    private void addLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLanguageButtonActionPerformed
        
        actions.addLanguageAction();

    }//GEN-LAST:event_addLanguageButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        actions.deleteAction();

    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addFunctionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFunctionButtonActionPerformed

        actions.addCommandAction();

    }//GEN-LAST:event_addFunctionButtonActionPerformed
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFunctionButton;
    private javax.swing.JButton addLanguageButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteLanguageButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    
    public void addNotify() {
        super.addNotify();
        try {
            //same problem as in 31086, initial focus on Cancel button
            manager.setSelectedNodes(manager.getRootContext().getChildren().getNodes());
        } catch (PropertyVetoException ex) {
            LogWriter.getLogWriter().printStackTrace(ex);
        }
    }
    
    boolean valid(WizardDescriptor wizardDescriptor) {
        Node node = manager.getRootContext();
        AddOn addon = (AddOn)node.getLookup().lookup(NbNodeObject.class);
        NbNodeObject[]commands = addon.getAllCommands();
        if (commands.length == 0) {
            String message = NbBundle.getMessage(AddOnWizardIterator.class, "LBL_ErrorMessageOneCommand");
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
            return false;
        }
        HashSet<String>names = new HashSet<String>();
        for (int i = 0; i < commands.length; i++) {
            Command com = (Command)commands[i];
            try {
                String name = com.getSimpleProperty(com.PROPERTY_CONTAINER_NAME);
                // use hash set for checking if names are unique;
                // every element is only once inside
                names.add(name);
                if (names.size() != i + 1) {
                    String message = NbBundle.getMessage(AddOnWizardIterator.class, "LBL_ErrorMessageUniqueName");
                    wizardDescriptor.putProperty("WizardPanel_errorMessage", message); // NOI18N
                    return false;
                }
            } catch (UnknownOpenOfficeOrgPropertyException ex) {
                LogWriter.getLogWriter().printStackTrace(ex);
            }
        }
        wizardDescriptor.putProperty("WizardPanel_errorMessage", ""); // NOI18N
        return true;
    }
    
    void store(WizardDescriptor d) {
        Node node = manager.getRootContext();
        // first subnodes are functions
        NbNodeObject addOn = (NbNodeObject)node.getLookup().lookup(NbNodeObject.class);
        d.putProperty("AddOn", addOn); // NOI18N
        
//        NbNodeObject[] subNodes = addOn.getAllSubObjects();
//        d.putProperty("functionCount", new Integer(subNodes.length)); // NOI18N
//        for (int i=0; i<subNodes.length; i++) {
//            Vector<String> functionSignatureContainer = new Vector<String>();
//            Function function = (Function)subNodes[i];
//            try {
//                String retValue = function.getProperty(function.PROPERTY_Type).getValueForLanguage(-1);
//                functionSignatureContainer.add(retValue);
//                String funcName = function.getProperty(function.PROPERTY_Name).getValueForLanguage(-1);
//                functionSignatureContainer.add(funcName);
//                
//                // multilingual stuff
//                LocalizedOpenOfficeOrgProperty prop = (LocalizedOpenOfficeOrgProperty)function.getProperty(function.PROPERTY_DisplayName);
//                String[][]localProps = getLocalizedProperties(prop, funcName);
//                d.putProperty(funcName.concat("DisplayName"), localProps); // NOI18N
//
//            } catch (UnknownOpenOfficeOrgLanguageIDException ex) {
//                LogWriter.getLogWriter().printStackTrace(ex);
//            }
//            String[] functionArray = (String[])functionSignatureContainer.toArray(new String[functionSignatureContainer.size()]);
//            d.putProperty(new StringBuffer("function").append(i).toString(), functionArray); // NOI18N
//        }
    }
    
//    private String[][] getLocalizedProperties(LocalizedOpenOfficeOrgProperty prop, String defaultValue) {
//        if (defaultValue == null) defaultValue = ""; // NOI18N
//        Integer[] indexes = prop.getUsedLanguageIndexes();
//        String[][] retValue = new String[2][indexes.length];
//        for (int i=0; i<indexes.length; i++) {
//            int languageID = indexes[i].intValue();
//            String text = prop.getValueForLanguage(languageID);
//            String language = LanguageDefinition.getLanguageShortNameForId(languageID);
//            retValue[0][i] = language;
//            if (text != null && text.length() > 0 && text.charAt(0) != '<' 
//                            && text.charAt(text.length() - 1) != '>') {
//                retValue[1][i] = text;
//            }
//            else {
//                retValue[1][i] = defaultValue;
//            }
//        }
//        return retValue;
//    }
    
    void read(WizardDescriptor settings) {

        /*        File projectLocation = (File) settings.getProperty("projdir"); // NOI18N
        if (projectLocation == null || projectLocation.getParentFile() == null || !projectLocation.getParentFile().isDirectory()) {
            projectLocation = ProjectChooser.getProjectsFolder();
        } else {
            projectLocation = projectLocation.getParentFile();
        }
        this.projectLocationTextField.setText(projectLocation.getAbsolutePath());
        
        String projectName = (String) settings.getProperty("name"); // NOI18N
        if(projectName == null) {
            projectName = "AddOn"; // NOI18N
        }
        this.projectNameTextField.setText(projectName);
        this.projectNameTextField.selectAll(); */
    }
    
    void validate(WizardDescriptor d) throws WizardValidationException {
        // nothing to validate
    }

    public void propertyChange(PropertyChangeEvent evt) {
        // because of TreeSelectionModel.SINGLE_TREE_SELECTION max. one node is selected
        Node[] selectedNodes = manager.getSelectedNodes();
        if (selectedNodes.length > 0) {
            deleteButton.setEnabled(true);
        }
        else {
            deleteButton.setEnabled(false);
        }
        propSheet.setNodes(selectedNodes);
        panel.fireChangeEvent(); // Notify that the panel changed
    }
}
